volumes:
  rstudio-home-data:
    name: rstudio-home-data
  rstudio-tmp-data:
    name: rstudio-tmp-data
  gaia-solr:
    name: gaia-solr
  gaia-db:
    name: gaia-db

services:

  gaia-core: # built from hades image
    profiles: [ "gaia" ]
    image: gaia-core
    build:
      context: ${GAIA_CORE_GITHUB_URL}
      dockerfile: ./docker/gaia-core/Dockerfile
    container_name: gaia-core
    restart: unless-stopped
    secrets:
      - GAIA_PG_PASSWORD
      - HADES_PASSWORD
    environment:
      USER: ${HADES_USER}
      POSTGRES_USER: ${GAIA_PG_USER}
      POSTGRES_DB: ${GAIA_PG_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/GAIA_PG_PASSWORD
      POSTGRES_PORT: 5432
      GAIA_CORE_API_PORT: ${GAIA_CORE_API_PORT}
    ports:
      - "8787:8787"
      - "6311:6311"
    volumes:
      - rstudio-home-data:/home
      - rstudio-tmp-data:/tmp
      - ./hades/00_set_secrets:/etc/cont-init.d/00_set_secrets
    labels:
      - "traefik.enable=true"

  gaia-db:
    profiles: [ "gaia" ]
    image: gaia-db
    build:
      context: ${GAIA_DB_GITHUB_URL}
      dockerfile: ./Dockerfile
    container_name: gaia-db
    restart: unless-stopped
    secrets:
      - GAIA_PG_PASSWORD
    environment:
      POSTGRES_USER: ${GAIA_PG_USER}
      POSTGRES_DB: ${GAIA_PG_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/GAIA_PG_PASSWORD
      POSTGRES_PORT: 5432
    ports:
    - "${GAIA_PG_LOCALHOST_PORT}:5432"
    volumes:
      - gaia-db:/var/lib/postgresql/data

  gaia-catalog:
    profiles: [ "gaia" ]
    image: gaia-catalog
    # user: root
    build: 
      context: ${GAIA_CATALOG_GITHUB_URL}
      dockerfile: ./docker/repository/Dockerfile
    container_name: gaia-catalog
    restart: unless-stopped
    secrets:
      - GAIA_X_API_KEY
    environment:
      GAIA_X_API_KEY_FILE: /run/secrets/GAIA_X_API_KEY
      GAIA_POSTGIS_API_PORT: ${GAIA_POSTGIS_API_PORT}
      GAIA_OSGEO_API_PORT: ${GAIA_OSGEO_API_PORT}
      GAIA_GIT_API_PORT: ${GAIA_GIT_API_PORT}
      GAIA_GDSC_API_PORT: ${GAIA_GDSC_API_PORT}
    ports:
      - "${GAIA_CATALOG_API_PORT}:${GAIA_CATALOG_API_PORT}"
    depends_on:
      - gaia-solr
    #entrypoint: ["tail","-f","/dev/null"]
    entrypoint: sh -c "sleep 15 && python ohdsi.py"
    volumes:
      - ../gaiaCatalog/datastore/data:/data

  gaia-solr:
    profiles: [ "gaia" ]
    container_name: gaia-solr
    build: 
      context: ${GAIA_CATALOG_GITHUB_URL}
      dockerfile: ./docker/solr/Dockerfile
    image: gaia-solr
    restart: unless-stopped
    ports:
      - "${GAIA_SOLR_API_PORT}:${GAIA_SOLR_API_PORT}"
    volumes:
      - ../gaiaCatalog/datastore:/catalog
      - gaia-solr:/var/solr

  gaia-postgis:
    profiles: [ "gaia" ]
    image: gaia-postgis
    build:
      context: ./docker/
      dockerfile: ./gaia-postgis/Dockerfile
    container_name: gaia-postgis
    restart: unless-stopped
    secrets:
      - GAIA_X_API_KEY
      - GAIA_PG_PASSWORD
    environment:
      GAIA_X_API_KEY_FILE: /run/secrets/GAIA_X_API_KEY
      GAIA_POSTGIS_API_PORT: ${GAIA_POSTGIS_API_PORT}
      POSTGRES_USER: ${GAIA_PG_USER}
      POSTGRES_DB: ${GAIA_PG_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/GAIA_PG_PASSWORD
      POSTGRES_PORT: 5432
    # command: tail -f /dev/null
    ports:
      - "${GAIA_POSTGIS_API_PORT}:${GAIA_POSTGIS_API_PORT}"
    volumes:
      - ../gaiaCatalog/datastore/data:/data

  gaia-osgeo:
    profiles: [ "gaia" ]
    image: gaia-osgeo
    build:
      context: ./docker/
      dockerfile: ./gaia-osgeo/Dockerfile
    container_name: gaia-osgeo
    restart: unless-stopped
    secrets:
      - GAIA_X_API_KEY
      - GAIA_PG_PASSWORD
    environment:
      GAIA_X_API_KEY_FILE: /run/secrets/GAIA_X_API_KEY
      GAIA_OSGEO_API_PORT: ${GAIA_OSGEO_API_PORT}
      POSTGRES_USER: ${GAIA_PG_USER}
      POSTGRES_DB: ${GAIA_PG_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/GAIA_PG_PASSWORD
      POSTGRES_PORT: 5432
    # command: tail -f /dev/null
    ports:
      - "${GAIA_OSGEO_API_PORT}:${GAIA_OSGEO_API_PORT}"
    volumes:
      - ../gaiaCatalog/datastore/data:/data

  gaia-gdsc:
    profiles: [ "gaia" ]
    container_name: gaia-gdsc
    build: 
      context: ./docker/
      dockerfile: ./gaia-gdsc/Dockerfile
    image: gaia-gdsc
    restart: unless-stopped
    secrets:
      - GAIA_X_API_KEY
      - COPERNICUS_KEY
    environment:
      GAIA_X_API_KEY_FILE: /run/secrets/GAIA_X_API_KEY
      GAIA_COPERNICUS_KEY_FILE: /run/secrets/COPERNICUS_KEY
      GAIA_GDSC_API_PORT: ${GAIA_GDSC_API_PORT}
    ports:
      - "${GAIA_GDSC_API_PORT}:${GAIA_GDSC_API_PORT}"
    volumes:
      - ../gaiaCatalog/datastore/data:/data
    # command: tail -f /dev/null

  gaia-git:
    profiles: [ "gaia" ]
    container_name: gaia-git
    build: 
      context: ./docker/
      dockerfile: ./gaia-git/Dockerfile
    image: gaia-git
    restart: unless-stopped
    secrets:
      - GAIA_X_API_KEY
    environment:
      GAIA_X_API_KEY_FILE: /run/secrets/GAIA_X_API_KEY
      GAIA_GIT_API_PORT: ${GAIA_GIT_API_PORT}
    ports:
      - "${GAIA_GIT_API_PORT}:${GAIA_GIT_API_PORT}"
    volumes:
      - ../gaiaCatalog/datastore/data:/data
    # entrypoint: ["sh", "-c", "sleep 9999"]

  gaia-degauss:
    profiles: [ "degauss" ]
    container_name: gaia-degauss
    build:
      context: ${GAIA_DEGAUSS_GITHUB_URL}
    image: gaia-degauss
    restart: unless-stopped
    #entrypoint: ["bash", "-c", "sleep 9999"]
    entrypoint: ["Rscript","degauss.R"]
    command: []
    environment:
      GAIA_DEGAUSS_API_PORT: ${GAIA_DEGAUSS_API_PORT}
    ports:
      - "${GAIA_DEGAUSS_API_PORT}:${GAIA_DEGAUSS_API_PORT}"

secrets:
  HADES_PASSWORD:
    file: ${HADES_PASSWORD_FILE}
  GAIA_PG_PASSWORD:
    file: ${GAIA_PG_PASSWORD_FILE}
  GAIA_X_API_KEY:
    file: ${GAIA_X_API_KEY_FILE}
  COPERNICUS_KEY:
    file: ${GAIA_COPERNICUS_KEY_FILE}


  
